receivers:
processors:
  batch:
    send_batch_size: 10000
    timeout: 5s
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
exporters:
  logging:
service:
  pipelines:
    logs:
      receivers: []
      exporters: []
    metrics:
      receivers: []
      processors: [batch, resourcedetection/system]
      exporters: []
  telemetry:
    logs:
      level: "debug"
