name: upload release windows assets
on:
  release:
    types: [published]

jobs:
  upload_windows_assets:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Compress Agent
        run: |
          tar -czvf agent_windows.tar.gz -C ./scripts/windows .
      - name: Compress Kubernetes AKS
        run: |
          tar -czvf windows_kubernetes_aks.tar.gz -C ./datasources/windows ./kubernetes/aks -C . ./resources
      - name: Compress Kubernetes EKS
        run: |
          tar -czvf windows_kubernetes_eks.tar.gz -C ./datasources/windows ./kubernetes/eks -C . ./resources
      - name: Compress Kubernetes GKE
        run: |
          tar -czvf windows_kubernetes_gke.tar.gz -C ./datasources/windows ./kubernetes/gke -C . ./resources
      - name: Compress Localhost Windows
        run: |
          tar -czvf windows_localhost_windows.tar.gz -C ./datasources/windows ./localhost/windows -C . ./resources
      - name: Upload Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            agent_windows.tar.gz
            windows_kubernetes_aks.tar.gz
            windows_kubernetes_eks.tar.gz
            windows_kubernetes_gke.tar.gz
            windows_localhost_windows.tar.gz
